import { Knowledge, DataSource } from '@botpress/runtime'

/**
 * Per-charity markdown documents under `agent/data/charities/<id>.md` are
 * generated by `scripts/ingest-charities.ts`. The Botpress KB indexes each as
 * a separate passage so search citations come back per-charity (the file stem
 * is the charity ID).
 */
export default new Knowledge({
  name: 'charities',
  description:
    'Canadian charities (CRA-registered). Each document covers one charity: ' +
    'organization name, type, designation, location, tags, mission description, ' +
    'and high-level financials. Search this when matching a donor profile or a ' +
    'free-form donor prompt to charities.',
  sources: [
    DataSource.Directory.fromPath('./data/charities', {
      filter: (filePath) => filePath.endsWith('.md'),
    }),
  ],
})
